level-1:
  Rare: 1-3
  Epic: 3-5
  EpicWarforged: 6-10
  EpicTitanforged: 10-12
level-2:
  Rare: 6-8
  Epic: 9-12
  EpicWarforged: 13-15
  EpicTitanforged: 15-20
level-3:
  Rare: 8-11
  Epic: 11-14
  EpicWarforged: 15-20
  EpicTitanforged: 20-30
level-4:
  Rare: 11-14
  Epic: 15-18
  EpicWarforged: 20-24
  EpicTitanforged: 26-31